#!/bin/bash

# This script encodes a given JSON file into a Base64 string and saves it
# into a .env-style file for use with the application.

# --- Configuration ---
INPUT_JSON_FILE=$1
OUTPUT_ENV_FILE=".env.generated"
ENV_VAR_NAME="VITE_QUIZ_JSON_CONTENT"

# --- Main Logic ---

# 1. Validate input
if [ -z "$INPUT_JSON_FILE" ]; then
  echo "❌ Error: No input file provided."
  echo "Usage: ./create_env_from_json.sh <path_to_your_json_file>"
  exit 1
fi

if [ ! -f "$INPUT_JSON_FILE" ]; then
  echo "❌ Error: Input file not found at '$INPUT_JSON_FILE'"
  exit 1
fi

# 2. Encode the file content
echo "🔄 Encoding '$INPUT_JSON_FILE'..."
BASE64_CONTENT=$(base64 -i "$INPUT_JSON_FILE")

if [ -z "$BASE64_CONTENT" ]; then
    echo "❌ Error: Failed to encode file content. The file might be empty."
    exit 1
fi

# 3. Write to the output file
echo "📝 Writing encoded content to '$OUTPUT_ENV_FILE'..."
echo "# Auto-generated by create_env_from_json.sh on $(date)" > "$OUTPUT_ENV_FILE"
echo "# Content of: $INPUT_JSON_FILE" >> "$OUTPUT_ENV_FILE"
echo "" >> "$OUTPUT_ENV_FILE"
echo "$ENV_VAR_NAME=$BASE64_CONTENT" >> "$OUTPUT_ENV_FILE"

echo "✅ Success! Encoded content saved to '$OUTPUT_ENV_FILE'."
echo "➡️ Next steps:"
echo "   1. Copy the content of '$OUTPUT_ENV_FILE' into your main .env file."
echo "   2. Update your VITE_QUIZ_JSON_CONTENT GitHub Secret with the same value." 